# Generated by Django 4.2.27 on 2026-01-21 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرابط')),
                ('description', tinymce.models.HTMLField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fa-landmark', help_text='FontAwesome icon class (مثل: fa-mosque, fa-cross)', max_length=50, verbose_name='أيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قسم سياحي',
                'verbose_name_plural': 'الأقسام السياحية',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='الرابط')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة / المنطقة')),
                ('short_description', models.TextField(max_length=300, verbose_name='وصف مختصر')),
                ('description', tinymce.models.HTMLField(verbose_name='الوصف التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='مثال: 30.047778', max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='مثال: 31.233889', max_digits=9, null=True, verbose_name='خط الطول')),
                ('suggested_duration', models.IntegerField(choices=[(1, 'ساعة واحدة'), (2, 'ساعتان'), (3, '3 ساعات'), (4, '4 ساعات'), (5, '5 ساعات'), (6, 'نصف يوم'), (8, 'يوم كامل'), (12, 'يوم ونصف'), (16, 'يومان')], default=3, verbose_name='مدة الزيارة المقترحة (بالساعات)')),
                ('visitor_tips', tinymce.models.HTMLField(blank=True, verbose_name='نصائح للزائر')),
                ('best_time_to_visit', models.CharField(blank=True, help_text='مثال: الشتاء، الصباح الباكر', max_length=200, verbose_name='أفضل وقت للزيارة')),
                ('entry_fee', models.CharField(blank=True, help_text='مثال: 200 جنيه للأجانب، 50 جنيه للمصريين', max_length=100, verbose_name='رسوم الدخول')),
                ('priority', models.IntegerField(default=5, help_text='1 = أعلى أولوية، 10 = أقل أولوية', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='الأولوية')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('view_count', models.IntegerField(default=0, editable=False, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tourism.category', verbose_name='القسم السياحي')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tourism.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'موقع سياحي',
                'verbose_name_plural': 'المواقع السياحية',
                'ordering': ['priority', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البرنامج')),
                ('duration_days', models.IntegerField(verbose_name='عدد الأيام')),
                ('description', models.TextField(blank=True, verbose_name='وصف البرنامج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='tourism.category', verbose_name='القسم السياحي')),
            ],
            options={
                'verbose_name': 'برنامج سياحي',
                'verbose_name_plural': 'البرامج السياحية',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/%Y/%m/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.touristplace', verbose_name='الموقع السياحي')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tourism.touristplace', verbose_name='الموقع المعني')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='رقم اليوم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اليوم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('places', models.ManyToManyField(related_name='program_days', to='tourism.touristplace', verbose_name='المواقع السياحية')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tourism.tourprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'يوم في البرنامج',
                'verbose_name_plural': 'أيام البرنامج',
                'ordering': ['program', 'day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
    ]
