# Generated by Django 4.2.27 on 2026-01-21 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='رقم اليوم')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='وقت الزيارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.touristplace')),
            ],
            options={
                'verbose_name': 'يوم في خطة الرحلة',
                'verbose_name_plural': 'أيام خطة الرحلة',
                'ordering': ['trip_plan', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='UserTripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرحلة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الرحلة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الميزانية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('planned', 'مخطط'), ('in_progress', 'جاري التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('places', models.ManyToManyField(related_name='in_plans', through='tourism.TripPlanDay', to='tourism.touristplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خطة رحلة',
                'verbose_name_plural': 'خطط الرحلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='البلد')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة عني')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddField(
            model_name='tripplanday',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tourism.usertripplan'),
        ),
        migrations.AlterUniqueTogether(
            name='tripplanday',
            unique_together={('trip_plan', 'day_number', 'place')},
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tourism.touristplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مكان محفوظ',
                'verbose_name_plural': 'الأماكن المحفوظة',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
