# Generated by Django 4.2.27 on 2026-01-31 13:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_tripplanday_usertripplan_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الصورة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='best_time_to_visit_en',
            field=models.CharField(blank=True, help_text='Example: Winter, Early morning', max_length=200, verbose_name='أفضل وقت للزيارة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة / المنطقة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='الوصف التفصيلي (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='entry_fee_en',
            field=models.CharField(blank=True, help_text='Example: 200 EGP for foreigners, 50 EGP for Egyptians', max_length=100, verbose_name='رسوم الدخول (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='وصف مختصر (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='visitor_tips_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='نصائح للزائر (إنجليزي)'),
        ),
    ]
